version: '3'
services:
  front:
    container_name: telegram-bot-front
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    command: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    
  back:
    container_name: telegram-bot-back
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "3003:3000"
    command: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
    restart: unless-stopped
    depends_on:
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  redis:
    container_name: telegram-bot-redis
    image: redis:alpine
    ports:
      - "6379:6379"
