version: '3'
services:
  front:
    container_name: telegram-bot-front
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
    - "3002:3000"
    
  back:
    container_name: telegram-bot-back
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
    - "3003:3000"
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  redis:
    container_name: telegram-bot-redis
    image: redis:alpine
    ports:
      - "6379:6379"
