version: '2'
services:
  telegram-bot-front:
    build:
      context: .
    container_name: telegram-bot-front
    ports:
    - "3002:3000"
    command: npm start

  telegram-bot-back:
    build:
      context: backend
      dockerfile: ../Dockerfile
    container_name: telegram-bot-back
    ports:
    - "3003:3000"
    depends_on:
      - telegram-bot-redis
    environment:
      - REDIS_URL=redis://telegram-bot-redis:6379

  telegram-bot-redis:
    image: redis:alpine
    container_name: telegram-bot-redis
    ports:
      - "6379:6379"
